#!/usr/bin/env bash

OVERLORD_LOGS="${OVERLORD_LOGS:-/var/log/git}"

if [[ "$(basename $0)" == "overlord" ]]
then
    if [ -z "$1" ]
    then
        >&2 echo "HOOK-NAME is missing
usage: $0 HOOK-NAME [HOOK-NAME]..."
        exit 1
    fi

    HOOKDIR="$(dirname $0)"
    for h in $@
    do
        HOOK="$HOOKDIR/$h"
        ln -s "$0" "$HOOK"
        mkdir -p "$HOOK".d
    done
    exit 0
fi

HOOKS="$0".d
mkdir -p "$HOOKS"
[ -z "$(ls $HOOKS)" ] && exit 0

HOOK="$(basename $0)"
BG_HOOKS=(
    "post-applypatch"
    "post-commit"
    "post-merge"
    "post-receive"
    "post-update"
    "p4-post-changelist"
)

if grep -qF "$HOOK" <<<"${BG_HOOKS[@]}"
then
    mkdir -p "$OVERLORD_LOGS"
    chmod 750 "$OVERLORD_LOGS"
    LOGFILE="$OVERLORD_LOGS/$HOOK.log"
    LOCKFILE="/tmp/$(tr '/' '_' <<<$0).lock"

    if [ ! -f "$LOCKFILE" ]
    then
        touch "$LOCKFILE"
        ($0 $@ <<<"$(cat)" 1>>"$LOGFILE" 2>&1 &)&
        exit 0
    else
        trap "rm $LOCKFILE" EXIT
    fi
fi

STDIN="$(cat)"
for h in $HOOKS/*
do
    if [ -x "$h" ]
    then
        echo "$STDIN" | $h $@ || exit $?
    fi
done
